# preload = ~/.SYSTEM_CONFIG/themes/tokyonight.png
# wallpaper = ,~/.SYSTEM_CONFIG/themes/tokyonight.png
splash = false
wallpaper {
	monitor = 
	path = ~/.SYSTEM_CONFIG/themes/tokyonight.png
	fit_mode = cover
} 
